name       : libofx
version    : 0.9.14
release    : 8
source     :
    - https://netcologne.dl.sourceforge.net/project/libofx/libofx/libofx-0.9.14.tar.gz : b82757bfa15b27c02fb39dfd017cdfe5af51a063ba15afe495dd1b7367ff290a
license    : GPL-2.0-or-later
component  : programming
summary    : An API designed to allow applications to very easily support OFX command responses
description: |
    LibOFX library - API designed to allow applications to very easily support OFX command responses, usually provided by financial institutions.
patterns   :
    - docs : [/usr/share/doc*]
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libxml++-2.6)
    - gnupg
    - opensp-devel
setup      : |
    %patch -p1 < $pkgfiles/Make-file-format-less-stringent.patch
    %patch -p1 < $pkgfiles/Fix-segfault-if-iconv-wasnt-initialized.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
