name       : libofx
version    : 0.9.15
release    : 11
source     :
    - https://netcologne.dl.sourceforge.net/project/libofx/libofx/libofx-0.9.15.tar.gz : e95c14e09fc37b331af3ef4ef7bea29eb8564a06982959fbd4bca7e331816144
license    : GPL-2.0-or-later
component  : programming
summary    : An API designed to allow applications to very easily support OFX command
    responses
description: |
    LibOFX library - API designed to allow applications to very easily support OFX command responses, usually provided by financial institutions.
patterns   :
    - docs : [/usr/share/doc*]
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libxml++-2.6)
    - gnupg
    - opensp-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
