name       : libofx
version    : 0.9.12
release    : 2
source     :
    - https://nchc.dl.sourceforge.net/project/libofx/libofx/libofx-0.9.12.tar.gz : c15fa062fa11e759eb6d8c7842191db2185ee1b221a3f75e9650e2849d7b7373
license    : GPL-2.0
component  : programming
summary    : An API designed to allow applications to very easily support OFX command responses
description: |
    An API designed to allow applications to very easily support OFX command responses
patterns   :
    - docs : [/usr/share/doc*]
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libxml++-2.6)
    - gnupg
    - opensp-devel
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2017-14731.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
