name       : libofx
version    : 0.9.10
release    : 1
source     :
    - http://netcologne.dl.sourceforge.net/project/libofx/libofx/0.9.10/libofx-0.9.10.tar.gz : 54e26a4944ef2785087cfd8ed8f187ab9d397d9b92b5acc199dd7d5d095cf695
license    : GPL-2.0
component  : programming
summary    : An API designed to allow applications to very easily support OFX command responses
description: |
    An API designed to allow applications to very easily support OFX command responses
patterns   :
    - docs: [/usr/share/doc*]
builddeps  :
    - pkgconfig(libxml++-2.6)
    - curl
    - gnupg
    - opensp-devel
setup      : |
    %configure --disable-static
build      : |
    %make CXXFLAGS+=-std=c++11
install    : |
    %make_install
